# Generated by Django 4.1.4 on 2023-03-20 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_slug_product_prod_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='cat_offer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='prod_offer',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
