# Generated by Django 4.1.4 on 2023-03-20 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_cat_offer_product_prod_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prod_offer',
            new_name='p_offer',
        ),
    ]
