# Generated by Django 4.1.4 on 2023-03-20 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_prod_offer_product_p_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_offer',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_offer',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
