# Generated by Django 4.1.4 on 2023-03-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_user_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_offer',
            field=models.FloatField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_offer',
            field=models.FloatField(blank=True, default=True),
        ),
    ]
