# Generated by Django 4.1.4 on 2023-03-23 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_product_user_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_offer',
            field=models.FloatField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_offer',
            field=models.FloatField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='user_price',
            field=models.FloatField(blank=True, default=False),
        ),
    ]
