# Generated by Django 4.1.4 on 2023-03-28 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_rename_slug_category_cat_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='c_offer',
            field=models.BooleanField(default=False),
        ),
    ]
