# Generated by Django 4.1.4 on 2023-03-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_product_offer_cat_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='cat_offer',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='product_offer',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='product_offer',
            name='start_date',
        ),
    ]
