# Generated by Django 4.1.4 on 2023-04-03 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0003_remove_cat_offer_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='limited_price',
            field=models.IntegerField(null=True),
        ),
    ]
