# Generated by Django 4.1.4 on 2023-04-04 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='wish_id',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
