# Generated by Django 4.1.4 on 2023-01-12 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pay_id',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_method',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
