# Generated by Django 4.1.4 on 2023-01-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_pay_id_order_pay_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='pay_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pay_method',
        ),
        migrations.AlterField(
            model_name='order',
            name='ip',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
